import{a as m,S as f}from"./assets/vendor-2591be5d.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function d(t,n=1,o=15){const e=`https://pixabay.com/api/?key=43059810-21766dfeafea29ca9c24ae0e2&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${o}`;try{return(await m.get(e)).data.hits}catch(r){return console.error("Error fetching data:",r),[]}}function u(t,n){const o=document.getElementById("gallery");t.forEach(e=>{const r=`
      <div class="card">
        <a href="${e.largeImageURL}" data-lightbox="image">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="info">
          <p><strong>Likes</strong> <br>${e.likes}</p>
          <p><strong>Views</strong> <br>${e.views}</p>
          <p><strong>Comments</strong> <br>${e.comments}</p>
          <p><strong>Downloads</strong> <br>${e.downloads}</p>
        </div>
      </div>
    `;o.insertAdjacentHTML("beforeend",r)}),new f("#gallery a",{}).refresh(),o.children.length>=n&&(y(),h())}function y(){const t=document.getElementById("load-more-btn");t.style.display="none"}function h(){const t=document.getElementById("end-message");t.style.display="block"}const p=document.getElementById("search-form"),a=document.getElementById("loader"),l=document.getElementById("load-more-btn"),b=document.getElementById("end-message");let g="",i=1;p.addEventListener("submit",async t=>{t.preventDefault();const o=document.getElementById("search-input").value.trim();if(!o){iziToast.error({title:"Error",message:"Please enter a search query!"});return}g=o,i=1,a.classList.remove("hidden");const s=document.getElementById("gallery");s.innerHTML="";try{const e=await d(o),r=e.totalHits;u(e,r),l.style.display="block"}catch(e){console.error("Error searching for images:",e)}finally{a.classList.add("hidden")}});function L(){const t=document.querySelector(".card");return t?t.getBoundingClientRect().height:0}function E(){const t=L();t!==0&&window.scrollBy({top:t*2,behavior:"smooth"})}l.addEventListener("click",async()=>{a.classList.remove("hidden");try{const t=await d(g,i+1);u(t),i++,t.length===0&&(B(),I()),E()}catch(t){console.error("Error loading more images:",t)}finally{a.classList.add("hidden")}});function B(){l.style.display="none"}function I(){b.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
